### ISSUE TITLE
How do I put my username

### ISSUE THREAD

**Issue by rodrigo081089** [danielhoherd/plexdl#15]
I have no idea how to log in, or where is the config file. THanks for the help

**Comment by danielhoherd** [comment]
@rodrigo081089 are you familiar with command line tools in general? there's help text in the tool itself, and [the docs show example usage](https://github.com/danielhoherd/plexdl#run-via-docker)

**Comment by rodrigo081089** [comment]
Thanks, I did it. Is anyway to search a library instead of a series or movie name?

**Comment by danielhoherd** [comment]
@rodrigo081089 there's currently no way to limit what libraries are searched. This is a planned feature though, but development on this project is quite slow.

**Comment by rodrigo081089** [comment]
Sorry, I meant get all the links from one library or all links on a server

**Comment by danielhoherd** [comment]
@rodrigo081089 no, I had never considered such a feature. What is your use case?

**Comment by rodrigo081089** [comment]
I have a pkex share and there is a cartoon library I want to download completily

**Comment by danielhoherd** [comment]
@rodrigo081089 this functionality is not supported, and i'm not sure it's possible. The software relies on the plex api, and I don't know of a way to get a full listing of a library from the plex api.

<https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.search>

The docs say that the search string is optional, so I'll play with it next time I'm working on the software. I wouldn't hold my breath if I were you, but we'll see how it goes.

**Comment by danielhoherd** [comment]
I'm closing this issue because the thread has wandered away from the original description. I'm keeping it in mind though for whenever I work on this software again.
