### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by Cyber5imon** [danielhoherd/plexdl#42]
2FA is not supported.
Add ability to submit 2FA code as a command line option.

**Comment by danielhoherd** [comment]
This is still planned.

**Comment by mancube** [comment]
If you add your 2FA code on the end of the password, no spaces or anything, you can still log in as expected, try it!
@SPDurkee

**Comment by Cyber5imon** [comment]
Should the "feature" to append the 2FA code to the end of your password be documented somewhere?

**Comment by danielhoherd** [comment]
@Cyber5imon https://support.plex.tv/articles/two-factor-authentication/#toc-1

> In the very rare case where you’re using a Plex app that doesn’t directly support 2FA verification (which typically means it’s a third-party app or tool that isn’t using our standard authentication methods), you can still sign in via 2FA. Specifically, you append a valid verification code to the end of the password when submitting: `<password><verification code>`
